name: Build

on:
  push:
    branches: ["main", "beta"]
    paths:
      - "**"
      - "!LICENSE"
      - "!README.md"
      - "!.gitattributes"
      - "!.gitignore"
      - "!.prettierignore"
      - "!.editorconfig"
      - "!.vscode"
      - "!.idea"
      - "!package.json"
      - "!bun.lockb"
      - "!**.log"
#   pull_request:
#     branches: [ "v4", "main" ]
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment per branch
concurrency:
  group: "pages-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add git author
        uses: fregante/setup-git-user@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: build
        run: bun run build

      # Устанавливаем custom domain для Pages через CNAME внутри ./dist
      - name: Set Pages custom domain
        run: |
          case "$GITHUB_REF" in
            refs/heads/main)
              echo "assets.ic10.dev" > ./dist/CNAME
              ;;
            refs/heads/beta)
              echo "assets-beta.ic10.dev" > ./dist/CNAME
              ;;
            *)
              echo "No custom domain for $GITHUB_REF"
              ;;
          esac

      #   - name: Pack
      #     id: build
      #     run:  echo "OUTPUT=$(npm pack)" 1> "$GITHUB_OUTPUT"

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist repository
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3